name: Coveralls test

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env: 
      COVERALLS_REPO_TOKEN: "${{ secrets.GITHUB_TOKEN  }}"
      COVERALLS_GIT_BRANCH: "${{ github.ref }}"

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies and test
        run: |
          npm ci
          npm run test:coverage:report
          ls -la
          pwd
