name: Coveralls test

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
        env:
          CI: true

      - uses: actions/checkout@v2
      - name: Coveralls 
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run test:coverage:report
