name: Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CI: true
    - run: |
        npm ci
        npm run build
        sudo bash < $(curl -s -N "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" | tar zxOf -)/install
        aws s3 sync ./dist s3://conway.reinisch.io
