name: Simple

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build:
        name: Execute remote commands
        runs-on: ubuntu-latest

        steps:
            - run: echo 123
