name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /home/node
          git clone https://github.com/Simonwep/intl-demo
          cd intl-demo
          npm i
          npm run build
          rm -rf /var/www/app/intl
          mkdir /var/www/app/intl
          mv dist/* /var/www/app/intl
          echo "Done!"
